.TH huayra-tdapplet 1 "28 Junio 2017" "Huayra Utils" "Huayra Theft Deterrent Applet"
.SH NOMBRE
huayra-tdapplet \- Aplicación que notifica los cambios de Theft Deterrent
.SH DESCRIPCION
huayra-tdapplet es una aplicación que se registra como un ícono en la bandeja
de notificaciones y le avisa al usuario de cualquier cambio del Theft Deterrent
(vencimiento próximo de certificados, estado de la conexión al servidor escolar, etc).
.SH VER TAMBIÉN
theftdeterrentclient(1)
.SH FALLOS
La aplicación depende de un buen funcionamiento del theftdeterrentclient,
cualquier bug allí puede hacerla funcionar errádicamente.
.SH AUTOR
Ignacio Losggio (iglosiggio@gmail.com).
